### ISSUE TITLE
homeWorkDanaShop

### ISSUE THREAD

**Issue by dilyarakhabibullina** [dilyarakhabibullina/homeWorkDanaShop#1]
Добрый день!
В проекте магазина пытаюсь сделать добавление метода, который будет создавать товары по отдельности, в данном случае- юбку. Идея подчеркивает аргументы (nextId, name, size, color, length, style, brand) в круглых скобках на второй строке, не могу понять почему. Если убрать аргументы, то в веб-сервисе карточка добавляется, но она без значений.

public void createSkirt(String name, int price, int size, String color, String length, String style, String brand) {
        Skirts item = new Skirts(nextId, name, size, color, length, style, brand);
        repository.add(item);
        nextId++;
    }

**Comment by coursar** [comment]
Потому что в классе Skirts у вас нет конструктора, вам нужно там создать конструктор и потом правильно его вызвать.
